<?php

namespace AppBundle\Repository;

/**
 * InsightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsightRepository extends \Doctrine\ORM\EntityRepository
{
}
