<?php

namespace AppBundle\Entity;

use AppBundle\Controller\Api\ChargeController;
use AppBundle\Entity\Traits\CreatedAtTrait;
use AppBundle\Enums\ChargePayerTypeEnum;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;


/**
 * Charge entity representing a single billable healthcare event.
 *
 * A charge is the central entity in revenue integrity analysis. It captures
 * procedure codes, amounts, payer information, and links to patient, department,
 * and diagnosis records. The Rules Engine evaluates charges to generate Insights.
 *
 * @see Insight for rule-generated findings
 * @see Rule for compliance and validation rules
 * @see Diagnosis for ICD-10 diagnosis codes (many-to-many)
 * @see ProcedureCode for CPT/HCPCS procedure codes (many-to-many)
 */
class Charge
{
    use CreatedAtTrait;

    /**
     * @var int
     */
    private $id;

    /**
     * Collection of CPT/HCPCS procedure codes.
     *
     * Codes may include modifiers (e.g., "99213-25", "70553-TC").
     *
     * @var Collection|ProcedureCode[]
     */
    private $procedureCodes;

    /**
     * @var int Charge amount in cents
     */
    private $chargeAmountCents;

    /**
     * @var string
     * @see ChargePayerTypeEnum
     */
    private $payerType;

    /**
     * @var DateTime Date of service
     */
    private $serviceDate;

    /**
     * Collection of insights generated by the Rules Engine for this charge.
     *
     * @var Collection|Insight[]
     */
    private $insights;

    /**
     * Collection of ICD-10 diagnosis codes supporting this charge.
     *
     * Medical necessity requires appropriate diagnosis codes for procedures.
     *
     * @var Collection|Diagnosis[]
     */
    private $diagnoses;

    /**
     * Department that generated this charge.
     *
     * @var Department
     */
    private $department;

    /**
     * Patient associated with this charge.
     *
     * @var Patient
     */
    private $patient;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->insights = new ArrayCollection();
        $this->diagnoses = new ArrayCollection();
        $this->procedureCodes = new ArrayCollection();
    }

    /**
     * @return Department
     */
    public function getDepartment(): Department
    {
        return $this->department;
    }

    /**
     * @param Department $department
     */
    public function setDepartment(Department $department): void
    {
        $this->department = $department;
    }

    /**
     * @return Patient
     */
    public function getPatient(): Patient
    {
        return $this->patient;
    }

    /**
     * @param Patient $patient
     */
    public function setPatient(Patient $patient): void
    {
        $this->patient = $patient;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get chargeAmountCents.
     *
     * @return int
     */
    public function getChargeAmountCents(): int
    {
        return $this->chargeAmountCents;
    }

    /**
     * Set chargeAmountCents.
     *
     * @param int $chargeAmountCents
     *
     * @return Charge
     */
    public function setChargeAmountCents(int $chargeAmountCents): self
    {
        $this->chargeAmountCents = $chargeAmountCents;

        return $this;
    }

    /**
     * Get payerType.
     *
     * @return string
     */
    public function getPayerType()
    {
        return $this->payerType;
    }

    /**
     * Set payerType.
     *
     * @param string $payerType
     * @return Charge
     * @see ChargePayerTypeEnum
     *
     */
    public function setPayerType(string $payerType): self
    {
        $this->payerType = ChargePayerTypeEnum::normalize($payerType);

        return $this;
    }

    /**
     * Get serviceDate.
     *
     * @return DateTime
     */
    public function getServiceDate(): DateTime
    {
        return $this->serviceDate;
    }

    /**
     * Set serviceDate.
     *
     * @param \DateTimeImmutable $serviceDate
     *
     * @return Charge
     */
    public function setServiceDate(\DateTimeImmutable $serviceDate): self
    {
        $this->serviceDate = $serviceDate;

        return $this;
    }

    /**
     * Add insight.
     *
     * @param Insight $insight
     *
     * @return Charge
     */
    public function addInsight(Insight $insight): self
    {
        if (!$this->insights->contains($insight)) {
            $this->insights[] = $insight;
            $insight->setCharge($this);
        }

        return $this;
    }

    /**
     * Remove insight.
     *
     * @param Insight $insight
     *
     * @return Charge
     */
    public function removeInsight(Insight $insight): self
    {
        if ($this->insights->removeElement($insight)) {
            if ($insight->getCharge() === $this) {
                $insight->setCharge(null);
            }
        }

        return $this;
    }

    /**
     * Get insights.
     *
     * @return Collection|Insight[]
     */
    public function getInsights(): Collection
    {
        return $this->insights;
    }

    /**
     * Get diagnoses.
     *
     * @return Collection|Diagnosis[]
     */
    public function getDiagnoses(): Collection
    {
        return $this->diagnoses;
    }

    /**
     * Add diagnosis.
     *
     * @param Diagnosis $diagnosis
     *
     * @return Charge
     */
    public function addDiagnosis(Diagnosis $diagnosis): self
    {
        if (!$this->diagnoses->contains($diagnosis)) {
            $this->diagnoses[] = $diagnosis;
            $diagnosis->addCharge($this);
        }

        return $this;
    }

    /**
     * Remove diagnosis.
     *
     * @param Diagnosis $diagnosis
     *
     * @return Charge
     */
    public function removeDiagnosis(Diagnosis $diagnosis): self
    {
        if ($this->diagnoses->removeElement($diagnosis)) {
            $diagnosis->removeCharge($this);
        }

        return $this;
    }

    /**
     * Get procedure codes.
     *
     * @return Collection|ProcedureCode[]
     */
    public function getProcedureCodes(): Collection
    {
        return $this->procedureCodes;
    }

    /**
     * Add procedure code.
     *
     * @param ProcedureCode $procedureCode
     *
     * @return Charge
     */
    public function addProcedureCode(ProcedureCode $procedureCode): self
    {
        if (!$this->procedureCodes->contains($procedureCode)) {
            $this->procedureCodes[] = $procedureCode;
            $procedureCode->addCharge($this);
        }

        return $this;
    }

    /**
     * Remove procedure code.
     *
     * @param ProcedureCode $procedureCode
     *
     * @return Charge
     */
    public function removeProcedureCode(ProcedureCode $procedureCode): self
    {
        if ($this->procedureCodes->removeElement($procedureCode)) {
            $procedureCode->removeCharge($this);
        }

        return $this;
    }

    /**
     * Check if any procedure code has a specific modifier.
     *
     * @param string $modifier The modifier to check (e.g., "25", "59")
     *
     * @return bool
     */
    public function hasModifier(string $modifier): bool
    {
        foreach ($this->procedureCodes as $pc) {
            if ($pc->hasModifier($modifier)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Build evaluation context for the Rules Engine.
     *
     * Returns an array of charge data formatted for php-rule-parser evaluation.
     * Field names use snake_case to match YAML rule conditions.
     *
     * Includes:
     * - procedure_code: First CPT/HCPCS code (for single-code rules)
     * - procedure_codes: Array of all CPT/HCPCS codes (may include modifiers)
     * - diagnosis_codes: Array of ICD-10 diagnosis codes
     * - charge_amount_cents: Amount in cents
     * - payer_type: Payer category (MEDICARE, MEDICAID, etc.)
     * - department_code: Department identifier
     * - patient_type: Patient category (INPATIENT, OUTPATIENT, etc.)
     * - Computed fields: is_weekend, is_late_night, day_of_week, hour_of_day
     * - Modifier flags: has_modifier_25, has_modifier_59, has_modifier_tc, has_modifier_26
     *
     * @return array<string, mixed>
     */
    public function toRuleContext(): array
    {
        // Extract ICD-10 diagnosis codes from related entities
        $diagnosisCodes = [];
        foreach ($this->diagnoses as $diagnosis) {
            $diagnosisCodes[] = $diagnosis->getCode();
        }

        // Extract CPT/HCPCS procedure codes from related entities
        $procedureCodesArray = [];
        foreach ($this->procedureCodes as $pc) {
            $procedureCodesArray[] = $pc->getCode();
        }

        $serviceDate = $this->getServiceDate();
        $dayOfWeek = (int) $serviceDate->format('N'); // 1=Mon, 7=Sun
        $hour = (int) $serviceDate->format('G');

        return [
            // Core charge fields (CPT/HCPCS)
            'procedure_code' => $procedureCodesArray[0] ?? '',
            'procedure_codes' => $procedureCodesArray,
            'charge_amount_cents' => $this->getChargeAmountCents(),
            'payer_type' => $this->getPayerType(),
            'service_date' => $serviceDate->format('Y-m-d'),

            // ICD-10 diagnosis codes (from many-to-many relationship)
            'diagnosis_codes' => $diagnosisCodes,

            // Related entities
            'department_code' => $this->getDepartment() ? $this->getDepartment()->getCode() : '',
            'patient_type' => $this->getPatient() ? $this->getPatient()->getType() : '',

            // Computed fields for rule convenience
            'is_weekend' => $dayOfWeek >= 6,
            'is_late_night' => $hour >= 22 || $hour < 6,
            'day_of_week' => $dayOfWeek,
            'hour_of_day' => $hour,

            // Modifier flags (computed from procedureCodes)
            'has_modifier_25' => $this->hasModifier('25'),
            'has_modifier_59' => $this->hasModifier('59'),
            'has_modifier_tc' => $this->hasModifier('TC'),
            'has_modifier_26' => $this->hasModifier('26'),

            // Placeholder fields for extended rules
            // These would be computed by additional services
            'same_day_count' => 1,
            'duplicate_count' => 0,
            'is_covered' => true,
        ];
    }
}
