<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\Collection;

/**
 * Department entity representing a hospital or clinic department.
 *
 * Departments are organizational units (e.g., Cardiology, Orthopedics) that
 * generate charges. Used for departmental reporting and rule-based filtering.
 *
 * @see Charge for billable healthcare events
 */
class Department
{
    /**
     * @var int
     */
    private $id;

    /**
     * Short department code (e.g., CARD, ORTH, EMER).
     *
     * @var string
     */
    private $code;

    /**
     * Full department name (e.g., Cardiology, Orthopedics).
     *
     * @var string
     */
    private $name;

    /**
     * Collection of charges generated by this department.
     *
     * @var Collection|Charge[]
     */
    private $charges;

    /**
     * @return Charge[]
     */
    public function getCharges(): array
    {
        return $this->charges;
    }

    /**
     * @param Charge[] $charges
     */
    public function setCharges(array $charges): void
    {
        $this->charges = $charges;
    }


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get code.
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set code.
     *
     * @param string $code
     *
     * @return Department
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return Department
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }
}
