<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Traits\CreatedAtTrait;
use AppBundle\Enums\RuleTypeEnum;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * Rule entity representing a compliance or validation rule.
 *
 * Rules are configuration-driven and stored as YAML definitions. The Rules Engine
 * evaluates each charge against active rules and generates Insights when conditions
 * match. Rules are persisted for auditability and deterministic evaluation.
 *
 * @see RuleTypeEnum for rule categories (ELIGIBILITY, PRICING, VALIDATION, AUTHORIZATION)
 * @see Insight for rule-generated findings
 */
class Rule
{
    use CreatedAtTrait;

    /**
     * @var int
     */
    private $id;

    /**
     * Rule type category.
     *
     * @var string
     * @see RuleTypeEnum (ELIGIBILITY, PRICING, VALIDATION, AUTHORIZATION)
     */
    private $type;

    /**
     * Human-readable rule description explaining what the rule checks.
     *
     * @var string
     */
    private $description;

    /**
     * YAML rule definition containing conditions, thresholds, and severity.
     *
     * Stored as CLOB in Oracle for complex rule configurations.
     *
     * @var string
     */
    private $definitionYaml;

    /**
     * Whether this rule is active and should be evaluated.
     *
     * Inactive rules are retained for audit history but not processed.
     *
     * @var bool
     */
    private $active;

    /**
     * Collection of insights generated by this rule.
     *
     * Each insight links back to both the triggering charge and this rule.
     *
     * @var Collection|Insight[]
     */
    private $insights;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->insights = new ArrayCollection();
    }


    /**
     * Get id.
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Get type.
     *
     * @return string
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Set type.
     *
     * @param string $type
     *
     * @return Rule
     */
    public function setType(string $type): self
    {
        $this->type = RuleTypeEnum::normalize($type);

        return $this;
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Set description.
     *
     * @param string $description
     *
     * @return Rule
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get definitionYaml.
     *
     * @return string
     */
    public function getDefinitionYaml(): string
    {
        return $this->definitionYaml;
    }

    /**
     * Set definitionYaml.
     *
     * @param string $definitionYaml
     *
     * @return Rule
     */
    public function setDefinitionYaml(string $definitionYaml): self
    {
        $this->definitionYaml = $definitionYaml;

        return $this;
    }

    /**
     * Get active.
     *
     * @return bool
     */
    public function getActive(): bool
    {
        return $this->active;
    }

    /**
     * Set active.
     *
     * @param bool $active
     *
     * @return Rule
     */
    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Add insight.
     *
     * @param Insight $insight
     *
     * @return Rule
     */
    public function addInsight(Insight $insight): self
    {
        if (!$this->insights->contains($insight)) {
            $this->insights[] = $insight;
            $insight->setRule($this);
        }

        return $this;
    }

    /**
     * Remove insight.
     *
     * @param Insight $insight
     *
     * @return Rule
     */
    public function removeInsight(Insight $insight): self
    {
        if ($this->insights->removeElement($insight)) {
            if ($insight->getRule() === $this) {
                $insight->setRule(null);
            }
        }

        return $this;
    }

    /**
     * Get insights.
     *
     * @return Collection|Insight[]
     */
    public function getInsights(): Collection
    {
        return $this->insights;
    }
}
